apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pack-storage
  namespace: monitoring-support
  labels:
    monitoring.cybertec.at/scope: customers
spec:
  groups:
    - name: pack.storage
      rules:
        - alert: DiskSpace90PercentUsed
          expr: pgwatch_rs_psutil_disk_percent{customer!="netclusive"} >= 90
          for: 2m30s
          labels:
            severity: critical
            team: dba
            priority: P1
          annotations:
            summary: "Disk at 90%"
            description: "Disk space is above 90%"

        - alert: DiskSpace85PercentUsed
          expr: >
            pgwatch_rs_psutil_disk_percent{customer!="netclusive"} >= 85
            AND pgwatch_rs_psutil_disk_percent{customer!="netclusive"} < 90
          for: 5m
          labels:
            severity: warning
            team: dba
            priority: P1
          annotations:
            summary: "Disk at 85%"
            description: "Current free disk space is at 85%"
