---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pgx-conn
  namespace: target-customer-b
spec:
  encryptedData:
    password: AgBbBMw5u1dCeul8Ipn4R9zt6yiEpvOENw61n5nxnBqzpByPxnzZoHpLBUnx0soYvxEmGzd+Yr6R287JJl8LTIN51LYIJvpnfEEb8qOJMUGgQH30gwWBLDAArwz+/3lmezfa8EZmKvRZJiGKtY24VsVRMMeSjFx1W/BK1ZtSII03eMIHQuIhh5pRsXd0iKlH7QmpcHN0vmpe3gnt9hbWtu5EouEzuMFImMsNyrCcVqc+GiFMoQyL4ZSDkeMWGmffjR2a3rNAdGDnCmeupTMJ0x6SpBj2qQP8PGNfvXKF+JCJ0kJ7irY9etWPFtkosomalSAg3Elm7sxozeSsJeFE+xn74M1Ce9TT2OUBX/FNer1ucx3aoUDOuhkuabxJlAu1k4Zvx7vpsggil4onC7NXTy08T3R/63o2zuvhUE53/c381Lk285lpdE6eMyMfhg5+cTF1JAUmnUF6IDwKCwZJ/sJ3ZLhjVDqeZKSX59Ej3i1N992fYGh85OG4LjuPjCDx3f25QLhh4AdQDye6Oqqmz3ZW+5NcvbRQzWRhrk+divwTIe2EuuGsKCOHmTHxrSdQ/dsWowPKQEwDcpa4uel7I0BKdN6ZMRA7kUS/ZiTaCniM6sUHDcgRzeS39jBFoy72Wtt2rTTyvJ+8kChLELstD/vH12MKzYeHetwF8jXUroajVO6yh2gxVXHNziw1ZkKhVcHtO/NzzJaYpAQ=
    username: AgCY2BAXYmIryf8wACR67QdOzv/KsoU+jVuxe3MTvU7/IQcfDguL1sUnM2AGn/PgrXL8DLQgEwgKEt3UHGyBWAZoMHEphK+wVujL0WT9elqcK7iz/gWPWfkKEO0Zu1p4XUFkYiCpQ7saytQ94Ya8MClRjynuSVY2UWCNhvlj7xwqnhOwaOvbpOrvUaxP9MPBzUsB7vwVcOhPLJEyjybMV191o0ueUo3D7j5iIAzHO+WOyamFUrJaow3nnMw3q8v6AhO23Kl+QydqqLaDvnJEfc6uPR6qMcEdrglceBrH3i1OK3dHCxK9ZkvPe+uwGSMGOWYzjkFuJJyT1gwABS2Xth4hp9KZEAxi4Qh7nQ2cZz8vKxxt0RMCE/Ddr4/NgP5KcLt7qZ4qCJDGHEzwfeBOTUlnkcjJVuNLmAdIMm1DtY6p/ZsxKKj0rnTAz11H/Z54eTclfGrISynxtCgMyaNNKGIszSQw+pGGMqBI4WvBk3HrKALksx+zgkUDIbcp9v5NutYRxcjRW1lO5oAMWyS6XIB/v2lJ2nTykkNdWYIErjocUjs08AyZ7FQSp6CaNNxw1p+qE5FkBQNQt/b3nxTuMChJN4yeAbu5G694gROHi3ZGlPQDdGJchIBD+UXGAiGhVR3T/WpTOIaZwp4ocdfF7NUUXU9eQ2jE4IVBwGAL/KlP53Jkze07/jlXAaXAfCV2VDIclw2uOQ==
  template:
    metadata:
      name: pgx-conn
      namespace: target-customer-b
    type: Opaque
