---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pgx-conn
  namespace: target-netclusive
spec:
  encryptedData:
    password: AgCm+EQPGorYzCPNEJ0SZxMgGoAU/FSlB0S8sFg3rTPdNaOl2fkM53p+ELk8889+8qysfKM8wCkpyiUrOjpv9m5HhaEx/MP2EXgIlE25DnMFO1ZOSvJzoPpwT8IgnPK4kYJ5H1VK00wHvA6aBvjqirj17a/pQwl3qEqlfWnziXk/EQiTwtRvR5DhHT2ufVb2mN+JZxVULtRyOWjOcv9effz/tE67gLTydv7nbva/5YGZIRlfJtRryuPHIRNVV/TsBxECTFJR04uVxGR7rMx7bBVGw9sJz5GvZX1qRwJ7Mi13I9AsqEiyHU3V4NfIm8SZGQw1+PSfkLPcwN7OXXAjd1eEmXrEBJxFw//oyGUCPKvoVCiXoBSmE6mdsQSKa+ydGqT2xn/JX2CjGC0sFCaiUz7F04/mKxV+8/VM20oad3hPh0taMst91FX9X3s6qcZLuuWInRjvTbHoFI9PH6m3IqSQjr4tnoCxr1waFAbWfXFGpzvCQXY1b8T+0d0MPu2s/0IO8ixNZ3PInm76d+Pqv/TPAV1owuT5Jydmw949pKPW3aoSsRuvKwBFydVRbq3tb9nrS+fFCewAKYRLukvvpRqN1NdsFX5uNO6GI2nhKMbUhkVQtzLlszqfqnDgpDp73YACCOFlRIQz765PYp8P+ZBgkUdBBPX81JGHviW9Wt1PsKeHSNSz7MAbrRNEiMmiASoTLHixMmbbApxm9qznBUY=
    username: AgBPMFqrKfTJP0lx8Yw1/WPiH1k/r8pVxOZ6dDlyYG9D6iQN6Qe+sbepitvzO9qYpIX5CvxFxpLrJN+xyCazaYByCmyUVBJkGcTgbJGKAVRguB5MfGDS9msNjHX1XUeYMiJHAI0sayWbotCAJjJpQQ2bysj//IONbvkx7cr35jO5NfJp6Tt5Zt5zirS1cM9+NB1qDhpeiiL20qVAHFdcDSyz3ps1tW1OIYMBRnQWf7SEKmbymVEEI6RSPMMO+7aHLhQ27wH+fzfw5ITVg9aoO1sUD9kWEKCEYbfl7DcOk+TT7dbSs2vkG9u5pDPAIl38IyP33Q7OympW5SrpJnNwL7y20kWLCDmlLUhljD4aeZKqtMilYkDn5/NVHRPR7C1RnpT29yTPF/QYa7BdnCynwdXhiML981+lTqOtXDoW+kGgKUN5ZzLpiD+ZY7eMw9FboG/z6LOGSoMiCLiXY2yd0XCU7ReZzEX7kBLyLbPqxSV+6ZdPFwsY+zrFEhfPwnTQoFbX25fwiLRbr+/9BP0ZiSTVhNOLhZCjRUKWha/6jbzz1jSkQfM9gmnsD++qxTsiEJAT0lcYdJ4JWi2aNfztjxUqhST3COT5PVYHBR6Qh9ftyZ7Qz+B7h1AkPCmotfcBBzJbQ+1oAl+hhOMCq5MfHPbJFj4et21PW1kQ6dWXiEKDGKmMVoxd8R81zoFGhI1T1BDmp+6dAhzxRw==
  template:
    metadata:
      name: pgx-conn
      namespace: target-netclusive
