---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pgx-conn
  namespace: target-netclusive
spec:
  encryptedData:
    password: AgC4qeCYo9+MEfDruBm2pb9vRgzLyOEwD65KATyDMa0jTT5RDaC6Y3y2pt84XBTtCE8Z4I5C72xNUHTITLiMlRM9NbXldVm1my7mB5IjD4yMIHtH0KzBusYxPouOkN3VxuU7mQSr7cjbBmY1AXCAxQs0bXmpd2wvrIhFDKSqFLvBmFvI8gcvs0BfUfPsmrbP2lLHMOeGYgUKVRa88DZbaSa8KauMIxl0B71Y4Epzq2R7aP8lt1kaWgdOYUktSpWh0V1+5Rrokr6fa3w8aB22xijO8xwB1rKCMOAxakLTVVVyE2iVXJaphyfe6hWdJpWiAAIXlG5+Ncymh/vejWSfuWqc9Gm+XoAw+SZMzmbQkWtr7LJDun/Y3GeAIBhPpW5oSfLvo+PI+CGkmuV3WdBvYerZKTReA2bzaWWvD4stUsqPU+6X+aUOi4ZBAncE6AHkiW/6BVCQs908Ss7NPAML0WTGDRqetvhDLuJ6W1strrCR5bzi52ReDsONo+tuob+3siPvoH32qCJsKt82t5XsPqfq9aAXl98WBmwpW/OBpSgoWGPOzB6P9IuIhyg0oC1Tys/TG3IMj+Ii1zNrZeZxeiX8hd0YnxltrAI/n2wc1dGvc7VGJ/HEKjyGC/Hrn7GWRFc4Qu4s94olDtmiQMw6GxvwlNLZCGkpjVo1wyxBz22FIo4Q6KXbQgrkZA/7Lt2t/5Ixdxgm+1VltLNSkNnLd8Y=
    username: AgCxzrR96A7jaZzQeqStnNAlWXuYfDSHGZGZq0r14m4jqj6PPgg7Ipi2H+g7lBXoOxMQZWj4wof+V13vxJ+LYYxxqFGa8sK+JOnxxh39bglejBJWK1GdRXrnnXavMBBGBfxpxrBnB/flu4hmzzW1DRv5ZLBzLfjgzrU89yV35fUADJhYF5pzFcgVohkf8hnOLmYwxRQa6WkG/lPjWGhgZWaZpK7IHM7TIfYN1dIk78/pdBY5hFN4pCLaLihbt62RZ5pMCgCwKlAf/GLWRhMx2JRRL1CcwuMSIdxr1YdL0xK75O0VK8cwUMeElJ2hpy4nrLu6Poad+0P/DQONs2kKfyuPw78yjiMSHNC6tbfmZTEsZ8rUEzTOPksD4K62mkqtHL25QeluclynNTGD5+c+rui3h396VkFU12Anm/37wDOeJZwRwRIABL3e164uuK0pXwbd/gCOpL+9YDIGtHKd7ADvH0UoP4tXBU4KQ2E5qi4mQBgdZ/7wPu3g1IV32CIZr7PTMocI4xSNaNPiuh2NiopWjQVXOr8jQJUeAtqDs5dkiEbFdLaqV2duMLv2mzLAf56t8JcorHB6UWBU+ChIyfnj4dFLJ1mye1MWffIusb+WjYHeIvMlcQ4OMuB8yhFfGJY72cTivwN5CPflwz/RaDxdXBPDHmOofcz3jCzvGfumayxLIP8rURCUlTWDNVsS5cSsmVuE3MjvBg==
  template:
    metadata:
      name: pgx-conn
      namespace: target-netclusive
