---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pgx-conn
  namespace: target-customer-a
spec:
  encryptedData:
    password: AgCHMC08f6dQbQkeDlWexsiqN65WB2qjwBOs8troBaAU/WXmPLvZGamUiIewpdcJIpQq0N3v4K820UvzQkpPXDxqnefLqLOh3Uy6tqVW/KqyP/2/sghbnacb6pc2rY/xye9+Gafu3PxD/ei7DYR97Yty4SuUOjmHoyx1wxIpcONYgCj659gwOm/odv5vr4eglV5A5GK9hvEZQzFLxjibSwVD0DXUwb2KNATBm7sQaECLayjU9Qapg30LizoyJMdHrnh6yt9XskpwE18A6Vvo9PXyJgHHiVaIFEumpngfoTwM5wWlavZejD83QF8Heoa0BuYMJ5Qo68nStrDVLx6DLZvja0TDD+08JO01O441lBNxzVllOT9loMD80sWlZn6rh2UzOfqzhItLSTCw74pa2wqt9eFM1/ayTXSvGkX2a4PBw4q+GLtUEZCXcgrNeOGAwgUvmSlomnfACCyqnMMrEj+pkSf1OTNw38C42txbQWOXKh5THgJUtrOjHfIiB87GtETHNPvfAEA0JFtM6b1BPe1Xq2H7BnyrlorMmpScq228E2nYMVO/40FqTOAdJhM4gH27agic+ppdS/aXxst2cCH4VR+U8RfmZt139e6HefYjpq+28hGiZLeHnORJGM+VKWU3yAx8O7waXOKevbfmIfHP25CS9C/SK25BlvhmrlZmRKIBPaO3e+12gwcHaJkNHztoM1gXpRq6xHdyNpiM
    username: AgCVzNYVnabbHmdFBwE80Q4MWRYUV1Eml5DuSkdbIg0288LYFU1DfgbK4l6v137InuKoTX+sN3Q+UVC5mCXW5L0bpmRXcaljmbiH1BHoLu1ExJUjq51xTjyY3C+px2gGOsehnTpAoTxVSzjEMHWUQAfoDMyHVxtjgVhoQhpI2Qrj9BGNcxv9kSLtnVNJu+R8h6M+wx9TgOcetGATTPrcpGVtCi8i++wePVnd3jqGsj/01nvRGP1XeDgL10aBJzsOtpR/0mkhqlnrsK0W2DePandGtkI+ff/g2mm3f/1nrPiVrB1TUIJ1ajDRShZnYDZozwScaNjo0jXTouNzSsWO4VJdRKWe0Aj6W9jHMRy/71VEflkwMBWpp2DXNFKOPrP12jsJU4z0NPooMPWTr6ANRogqopQliZ4jUDAlsMTg/h/ZRtlFiw9RZrHqIcpHffQLfMJtiDvK7V17wIJPPPQysQsq/QFF97xjQXZdvkGRijTBrxlaFx9amwUSdEZMN9K7g0QiQ0vVv8cRBS1ShPTh1NSgYw5mVGGZ/J9pwZuabxXsg/OToVKLPe/oCKRMTHHDCdV6Vj+cylPURZQHMMfdys5fskQ0ZXI8sTrxC4mYGnotHUAC+RbH9tPWHlv9BOotGRpXyRx0+RjmXnD8ySfn7CS1Vi91c5JwdSZiOjBZcqXn1rjbaVjgq+sUthv0qbrrWwat8lmQtGyL2w==
  template:
    metadata:
      name: pgx-conn
      namespace: target-customer-a
    type: Opaque
