apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../components/alerts/packs/latency
  - ../../../../components/alerts/packs/storage
  - ../../../../components/alerts/packs/db-health
  - ../../../../components/alerts/packs/pgwatch-health