---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pgx-conn
  namespace: target-vor
spec:
  encryptedData:
    password: AgCsPNwzkpJPh8m24ufsafvMbpV/L7Q3el89xuqp53A32r2krA5ij/O4E8sMv8K2/sz6xKE0+SU0wSia2zMxvlpsZBAVk5QFWUQPbfvjjxYz9qkQCY9JhVnWWGgVICrhXGPAHctfNJOhK7iN+Ro0VRzZmxAtUlG0gakhnQdRY+BL9IPWsYySMB9/63pmBxL784Ezwb7sQRgU/4eMyKOIDfYO487bDnqUrt9NMgwBRkiFq1AQa/rcfqip5QY9Qz6F1/hzJrr0eMOXL60/TJNheMb2iPFP5unAbESfsc/1b5jVu3vXr8Jt08F7cfd9PwUpR0FLJFnOB2u4Nfu47FYxPYuTDZdvB0drmVSb3UTgPkolSNzkNVyBaPZYPXtpf8MQAyGyLnSqSMiQjfI+nWOGOLeU34PiLGVXMAPJ4gdCA26AGW57R/y98v8eMNC8qdKFphMUzoKrgXsg+b37EaQkQylG9tPsKteSfWhOzOVyqBrwfzs1KVOi3aqL6Q6lD7td9CxpJM7ey4smiW2vdnwPVClPsADzms57na2FYg/n0k64sMCpxu/d54agNt2120EmVtPDneQTSvcGNVQrQJT68+z14UkhoZ8Cg++COSzmEwKaRa5LXpHcZ+jVliJDiAGcQaM45l68JEEi2hTbylkgMBj5Z/QY3NBGn/ThTyc/7VtJ++ohUu9LFhO593J7db/P7SzPwLGf1UbZVytUFCnvFkw=
    username: AgAZwdQMQhJRqxsa+8QqI0bvNMVcQuSB1D1FPw+RF1Aj6xWCIQUkCxFd+oGTfuSjIAB3QwxSEpBL/WkdTXYgvki/E0JuKVh7ElgcBs7sO1VeJR2yfcX+YJoP6k1hwWj9EIam5M+Z0eHSXwHKXrWzx3jl03uMyl3XG1HOs0oIXIXoT0YDViZovH7OV6XKEboBlOSjQtQIfxkM38GmsD1JJTbL6gKAD+D/0b7u9Tj29Z3+7NpMDhtOXWpiglsz1ibPcjrFyXQPNmtSUu29BEFUcblgt/h9XFlbg5nd9QnsENqbu6VSUIHzfKruSMTxexVjGaeNXJYr0aBR0GzNG6lMixWTqPxfPKFrBRzy+m6+JMCxe7Ma9wCso/35ngiEIsYpNpIUUUgyAgem4yK6DB2UYBh/ZrA1IDvvjzlgisBgnopfxWVMVz/mxV5xS3WLnVfW4bYzP2otEplBykJ/4w3lfAK+Br7eN3/Ib4PZjiph+z2YCKJGRfKqtDWKY1ojL5JFWYV+IDQ+9QRj/Okc3YD8hvxw9MFWE2fFhVX1Ik5KOc5EzkIn7Px/p600t5nYd4svwgEqlAvLNgetzzJVdF+vD2ukAtP6hwuRLS9FRh5HeY7KwknD9IEuLsknm/39jXse7ipxjezkroJwa0AwN3RUSE+n7FBnUSPmVmhjO9wo5ZH8WGPAdnl9XNOvze4w4vPgh3QxQswUgBJ8Ng==
  template:
    metadata:
      name: pgx-conn
      namespace: target-vor
