config:
  datasource:
    host: "161.35.28.217"
    port: "5432"
    database: "postgres"
    sslmode: "disable"   # or verify-full / disable, etc.
    userSecret:
      name: "pgx-conn"
      key: "username"
    passwordSecret:
      name: "pgx-conn"
      key: "password"

serviceMonitor:
  enabled: true
  labels:
    monitoring.cybertec.at/scope: customers
  additionalLabels:
    monitoring.cybertec.at/scope: customers
